import type { SiteSection } from "./types";

/** Order here is page order. The nav menu, palette and headings read from it. */
export const sections: SiteSection[] = [
  {
    id: "top",
    index: "00",
    method: "GET",
    path: "/",
    label: "Home",
    status: "200 OK",
    latencyMs: 12,
    title: { serif: "Somil", mono: "Athole" },
  },
  {
    id: "whoami",
    index: "01",
    method: "GET",
    path: "/whoami",
    label: "About",
    status: "200 OK",
    latencyMs: 8,
    title: { serif: "A bit", mono: "about me" },
  },
  {
    id: "work",
    index: "02",
    method: "GET",
    path: "/work/corefix",
    label: "Case study",
    status: "200 OK",
    latencyMs: 31,
    title: { serif: "What I build", mono: "at work" },
  },
  {
    id: "pipeline",
    index: "03",
    method: "TRACE",
    path: "/request",
    label: "Request pipeline",
    status: "200 OK",
    latencyMs: 48,
    title: { serif: "Follow a", mono: "request" },
  },
  {
    id: "projects",
    index: "04",
    method: "GET",
    path: "/projects",
    label: "Projects",
    status: "200 OK",
    latencyMs: 17,
    title: { serif: "Things I've", mono: "built" },
  },
  {
    id: "experience",
    index: "05",
    method: "GET",
    path: "/experience",
    label: "Experience",
    status: "200 OK",
    latencyMs: 22,
    title: { serif: "Where I've", mono: "worked" },
  },
  {
    id: "stack",
    index: "06",
    method: "cat",
    path: "package.json",
    label: "Stack",
    status: "exit 0",
    latencyMs: 3,
    title: { serif: "What I", mono: "work with" },
  },
  {
    id: "now",
    index: "07",
    method: "102",
    path: "Processing",
    label: "Now",
    status: "in progress",
    latencyMs: 0,
    title: { serif: "What I'm", mono: "learning" },
  },
  {
    id: "contact",
    index: "08",
    method: "POST",
    path: "/contact",
    label: "Contact",
    status: "ready",
    latencyMs: 0,
    title: { serif: "Send a", mono: "request" },
  },
];
